# Generated by Django 4.1.2 on 2022-10-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalCode', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('mobileNumber', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('sign', models.FileField(upload_to='')),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
    ]
