# Generated by Django 4.1.2 on 2022-10-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='group',
            field=models.CharField(choices=[('admin', 'مدیر'), ('dabir', 'دبیر'), ('user', 'کاربر')], max_length=50),
        ),
    ]
