# Generated by Django 4.1.3 on 2022-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_customuser_mobilenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='personalcode',
            field=models.CharField(help_text='حداکثر ۲۰ کارکتر فقط اعداد ۰تا۹', max_length=20, null=True),
        ),
    ]
