# Generated by Django 4.1.3 on 2022-11-20 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('nameplz', models.CharField(max_length=51)),
                ('sign', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sign', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PostAppoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='modir.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.root'),
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=20, verbose_name='عنوان نامه')),
                ('discription', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('ready_text', models.CharField(choices=[('test', 'test')], max_length=50)),
                ('size_letter', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], max_length=50)),
                ('Transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transcript', to='modir.level')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='modir.level')),
                ('receivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='modir.level')),
                ('secretariat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretariat', to='modir.level')),
                ('signatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatory', to='modir.level')),
            ],
        ),
    ]
