# Generated by Django 4.0.6 on 2022-09-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='sender',
        ),
        migrations.AddField(
            model_name='letter',
            name='position',
            field=models.CharField(choices=[('choice', 'انتخاب کنید'), ('ath-admin', 'مدیر اتوماسیون-رییس هییت مدیر'), ('ath-dabir', 'مدیر اتوماسیون-دبیر کل'), ('ath-karpardaz', 'مدیر اتوماسیون-کارپرداز و پیک'), ('ath-graphic', 'مدیر اتوماسیون-واحد گرافیک'), ('ath-dabirmarkazi', 'مدیر اتوماسیون-کارشناس دبیرخانه مرکزی'), ('ath-boss', 'مدیر اتوماسیون-رییس')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='signatory',
            field=models.CharField(choices=[('db-main', 'دبیرخانه مرکزی'), ('db-heiat', 'کاربر دبیرخانه-ریس هیات امنا'), ('nboss-heiat', 'نایب رییس هیات امنا'), ('boss-autoheiat', 'مدیر اتوماسیون-رییس هیات مدیره'), ('khazane', 'خزانه دار'), ('ath-dabirkol', 'مدیر اتوماسیون-دبیر کل'), ('boss-excute', 'مدیر اجرایی'), ('boss-dokhaniat', 'رییس مرکز تحقیقات کنترل دخانیات'), ('nboss-hmodir', 'نایب رییس هیت مدیره'), ('db-hamayesh', 'دبیر کل همایش'), ('boss-ath-dbmain', 'مدیر اتوماسیون -کارشناس دبیرخانه مرکزی'), ('test', 'تست')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
