# Generated by Django 4.1.3 on 2022-11-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='root',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
