# Generated by Django 4.0.6 on 2022-09-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0002_remove_letter_sender_letter_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='Transcript',
            field=models.CharField(choices=[('test', 'test')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='discription',
            field=models.CharField(default='توضیح', max_length=100, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='letter',
            name='ready_text',
            field=models.CharField(choices=[('test', 'test')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='receivers',
            field=models.CharField(choices=[('test', 'test')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='secretariat',
            field=models.CharField(choices=[('markaz_tahghigh', 'دبیرخانه مرکز تحقیقات'), ('hamayesh', 'دبیرخانه همایش')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='size_letter',
            field=models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='subtitle',
            field=models.CharField(default='نامه', max_length=20, verbose_name='عنوان نامه'),
        ),
    ]
