# Generated by Django 4.1.3 on 2022-11-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0003_dabirkhone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postappoinment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='modir.root'),
        ),
    ]
