# Generated by Django 4.0.6 on 2022-09-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0003_letter_transcript_letter_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='receivers',
            field=models.CharField(choices=[('test', 'test'), ('test2', 'test2'), ('test3', 'test3')], max_length=50, null=True),
        ),
    ]
