# Generated by Django 4.1.3 on 2022-12-01 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modir', '0004_alter_postappoinment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dabirkhone',
            name='choiceDabirKhone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
