# Generated by Django 4.0.6 on 2022-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0004_alter_letter_receivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='Transcript',
            field=models.CharField(choices=[('test', 'test'), ('test2', 'test2'), ('test3', 'test3'), ('test3', 'test3'), ('test3', 'test3'), ('test3', 'test3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='receivers',
            field=models.CharField(choices=[('test', 'test'), ('test2', 'test2'), ('test3', 'test3'), ('test3', 'test3'), ('test3', 'test3'), ('test3', 'test3')], max_length=50, null=True),
        ),
    ]
